services:
  ivoyager-web:
    build: .
    container_name: ivoyager-web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - ivoyager-ticker-ws

  ivoyager-ticker-ws:
    build: ./websocket-server
    container_name: ivoyager-ticker-ws
    restart: unless-stopped
    expose:
      - "3001"
    environment:
      - PORT=3001
